Repository Ishaan28malik/Get-Dev-Resources, pull requests merged in 2022-10, with the labels that each got.

#137 Update Machine-Learning-Resources.md
  Data-Science/Machine-Learning-Resources.md
Labels: hacktoberfest, hacktoberfest-accepted

#136 Update Back-end.md
  Software-Dev/Back-end.md
Labels: help wanted, hacktoberfest, hacktoberfest-accepted

#55 Small Contribution that i feel willl hellp a lot of devs when they se…
  Designer-Resources/Designer-main.md
  Software-Dev/Front-end.md
Labels: help wanted, hacktoberfest, hacktoberfest-accepted

#42 Update Designer-main.md
  Designer-Resources/Designer-main.md
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#40 Update Machine-Learning-Resources.md
  Data-Science/Machine-Learning-Resources.md
Labels: enhancement, help wanted, good first issue, hacktoberfest, hacktoberfest-accepted
